from flask import Flask, redirect
import os
import subprocess
from datetime import datetime
import pytz

app = Flask(__name__)

@app.route('/')
def home():
    """Redirect root URL to the /htop endpoint"""
    return redirect('/htop')

@app.route('/htop')
def htop():
    """System monitoring endpoint"""
    name = "Lambodar Maruti Naik" 
    username = os.getenv('USER', os.getenv('USERNAME', 'unknown'))
    
    ist = pytz.timezone('Asia/Kolkata')
    server_time = datetime.now(ist).strftime('%Y-%m-%d %H:%M:%S %Z')
    
    try:
        top_output = subprocess.check_output(
            ['top', '-b', '-n', '1'], 
            stderr=subprocess.STDOUT,
            timeout=3
        ).decode('utf-8')
    except subprocess.CalledProcessError:
        try:
            top_output = subprocess.check_output(
                ['ps', 'aux'],
                stderr=subprocess.STDOUT,
                timeout=3
            ).decode('utf-8')
        except Exception as e:
            top_output = f"Command failed: {str(e)}"

    return f"""
    <html>
    <head>
        <title>System Monitor</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            pre {{ background: #f4f4f4; padding: 10px; border-radius: 5px; }}
        </style>
    </head>
    <body>
        <h1>System Information</h1>
        <p><strong>Name:</strong> {name}</p>
        <p><strong>Username:</strong> {username}</p>
        <p><strong>Server Time (IST):</strong> {server_time}</p>
        
        <h2>Process Information</h2>
        <pre>{top_output}</pre>
        
        <footer>
            <p>Generated by Flask on GitHub Codespaces</p>
        </footer>
    </body>
    </html>
    """

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)